<?php
include('server.php');
// Verify if the user is logged in
if (!isset($_SESSION['correoCliente']) || !isset($_SESSION['role'])) {
    header("Location: login.php");
    exit();
}

// Verify if the user has the role 'admin'
if ($_SESSION['role'] !== 'admin') {
    // Redirect to client dashboard if not an admin
    header("Location: cliente_dashboard.php");
    exit();
}

if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['correoCliente']);
    header("location: login.php");
}

//Query to get all the flights, and feed them to options in the select tags for modify modal
$aeronaveQuery = "SELECT idaeronave, tipoAeronave FROM aeronave";
$aeronaveResult = $db->query($aeronaveQuery);

$aeropuertoQuery = "SELECT idAeropuerto, ciudadAeropuerto FROM aeropuerto";
$aeropuertoResult = $db->query($aeropuertoQuery);


if (isset($_POST['idaeronave'])) {
    $idaeronave = $_POST['idaeronave'];

    // Delete the record
    $sql = "DELETE FROM aeronave WHERE idaeronave = '$idaeronave'";
    if ($db->query($sql) === TRUE) {
        // Deletion successful
        // echo "Record deleted successfully";
    } else {
        // Error in deletion
        echo "Error deleting record: " . $db->error;
    }
} else {
    // echo "Invalid request";
}


?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/styles.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Francois+One&family=Wix+Madefor+Display:wght@400;500&display=swap" rel="stylesheet">
    <title>flightScanner</title>

    <style>

    </style>


</head>

<body>

    <?php include 'menu_admin.php'; ?>


    <div class="flightcontent">
        <?php
        if (isset($inserted) && $inserted) {
            echo ' <div style="background-color: #c6efce;
            color: #006100;
            padding: 10px;
            border: 1px solid #006100;
            border-radius: 5px;
            margin: 10px 0;" class="success-message">Aeronave insertada correctamente.</div>';
        }
        ?>
        <div class="input-group">
            <h2 style="color:#172554">Ingresa o Modifica Aeronaves</h2>
        </div>

        <!-- Vuelo table, generated by query -->
        <table border="1">
            <tr>
                <th>ID</th>
                <th>Tipo de Aeronave</th>
                <th>Rango de altitud</th>
                <th>Rango de Velocidad</th>
                <th></th>


            </tr>

            <?php
            //Query to generate vuelo table
            $sql = "SELECT * FROM aeronave";
            $result = $db->query($sql);

            if ($result->num_rows > 0) {
                while ($row = $result->fetch_assoc()) {
                    echo "<tr>";
                    echo "<td>" . $row["idaeronave"] . "</td>";
                    echo "<td>" . $row["tipoAeronave"] . "</td>";
                    echo "<td>" . $row["rangoAltitud"] . "</td>";
                    echo "<td>" . $row["rangoVelocidad"] . "</td>";
                    echo "<td><a href='#' class='delete-button' data-id='" . $row["idaeronave"] . "'>Borrar</a></td>";


                    echo "</tr>";
                }
            } else {
                echo "<tr><td colspan='9'>No data found</td></tr>";
            }
            ?>

        </table>
        <br>
        <a href='#' class='modify-button' onclick="  openInsertModalAeronave()">Agregar Aeronave</a>


        <!-- Modify modal, to confirm modification of table vuelos registry through ID -->

        <div id="insertAeronaveModal" class="modal">
            <div class="modal-content">
                <span class="close" id="modalClose">&times;</span>
                <form action="aeronaves_mod.php" method="POST">
                    <h2 style="color:#172554">Agregar Aeronave</h2>

                    <div class="input-group">
                        <label for="tipoAeronave">Tipo de Aeronave</label>
                        <input type="text" name="tipoAeronave" maxlength="20" id="tipoAeronave" required>
                    </div>
                    <div class="input-group">
                        <label for="rangoAltitud">Rango de Altitud</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" name="rangoAltitud" id="rangoAltitud" required>
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija el Rango de Altitud</option>
                            <option style="color: black; background-color: white;" value="Alta">Alta</option>
                            <option style="color: black; background-color: white;" value="Media">Media</option>
                            <option style="color: black; background-color: white;" value="Baja">Baja</option>
                        </select>
                    </div>
                    <div class="input-group">
                        <label for="rangoVelocidad">Rango de Velocidad</label>
                        <input type="text" name="rangoVelocidad" oninput="formatSpeed(this)" maxlength="30" id="rangoVelocidad" required>
                    </div>
                    <div class="modal-buttons">
                        <button type="submit" class="modify-button" name="agregar_aeronave" id="confirm">Guardar</button>
                        <button id="cancel" class="cancel-button">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>

        <script src="../js/script.js"></script>

        <script>
            document.addEventListener("DOMContentLoaded", function() {

                var deleteButtons = document.querySelectorAll(".delete-button");
                deleteButtons.forEach(function(button) {
                    button.addEventListener("click", function(event) {
                        event.preventDefault();
                        var idaeronave = button.getAttribute("data-id");
                        var confirmDelete = confirm("Desea borrar?");

                        if (confirmDelete) {
                            var xhr = new XMLHttpRequest();
                            xhr.open("POST", "aeronaves_mod.php", true);
                            xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                            xhr.onreadystatechange = function() {
                                if (xhr.readyState === XMLHttpRequest.DONE) {
                                    if (xhr.status === 200) {
                                        location.reload();
                                    } else {
                                        alert("Error deleting record.");
                                    }
                                }
                            };
                            xhr.send("idaeronave=" + idaeronave);
                        }
                    });
                });
            });




            function formatSpeed(input) {
                input.value = input.value.replace(/[^\d]/g, ''); // Remove non-numeric characters
                if (input.value.length > 0) {
                    input.value = input.value + ' km/h';
                }
            }
        </script>

</body>

</html>