<?php
include('server.php');
// Verify if the user is logged in
if (!isset($_SESSION['correoCliente']) || !isset($_SESSION['role'])) {
    header("Location: login.php");
    exit();
}

// Verify if the user has the role 'admin'
if ($_SESSION['role'] !== 'admin') {
    // Redirect to client dashboard if not an admin
    header("Location: cliente_dashboard.php");
    exit();
}

if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['correoCliente']);
    header("location: login.php");
}


if (isset($_POST['idAeropuerto'])) {
    // This is for deletion
    $idAeropuerto = $_POST['idAeropuerto'];

    // Delete the record
    $sql = "DELETE FROM aeropuerto WHERE idAeropuerto = '$idAeropuerto'";
    if ($db->query($sql) === TRUE) {
        echo "Record deleted successfully";
    } else {
        echo "Error deleting record: " . $db->error;
    }
} else {
    // echo "Invalid request";
}


?>





<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/styles.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Francois+One&family=Wix+Madefor+Display:wght@400;500&display=swap" rel="stylesheet">
    <title>flightScanner</title>

    <style>

    </style>


</head>

<body>

    <?php include 'menu_admin.php'; ?>


    <div class="flightcontent">
        <?php


        if (isset($inserted) && $inserted) {
            echo ' <div style="background-color: #c6efce;
            color: #006100;
            padding: 10px;
            border: 1px solid #006100;
            border-radius: 5px;
            margin: 10px 0;" class="success-message">Aeropuerto insertada correctamente.</div>';
        }
        ?>

        <?php
        if (count($errors) > 0) {
            echo '<div class="error">';
            foreach ($errors as $error) {
                echo '<p>' . $error . '</p>';
            }
            echo '</div>';
        }
        ?>


        <div class="input-group">
            <h2 style="color:#172554">Ingresa o Modifica Aeronaves</h2>
        </div>

        <!-- Vuelo table, generated by query -->
        <table border="1">
            <tr>
                <th>ID del aeropuerto</th>
                <th>Ciudad del Aeropuerto</th>
                <th>Modificar</th>


            </tr>

            <?php
            //Query to generate vuelo table
            $sql = "SELECT * FROM aeropuerto";
            $result = $db->query($sql);

            if ($result->num_rows > 0) {
                while ($row = $result->fetch_assoc()) {
                    echo "<tr>";
                    echo "<td>" . $row["idAeropuerto"] . "</td>";
                    echo "<td>" . $row["ciudadAeropuerto"] . "</td>";
                    echo "<td><a href='#' class='delete-button' data-id='" . $row["idAeropuerto"] . "'>Borrar</a></td>";
                    echo "</tr>";
                }
            } else {
                echo "<tr><td colspan='9'>No data found</td></tr>";
            }
            ?>

        </table>
        <br>
        <a href='#' class='modify-button' onclick='openInsertModalAeropuerto()'>Agregar Aeropuerto</a>


        <!-- Modify modal, to confirm modification of table vuelos registry through ID -->

        <div id="insertAeropuertoModal" class="modal">
            <div class="modal-content">
                <span class="close" id="modalClose">&times;</span>
                <form action="aeropuertos_mod.php" method="POST">
                    <div class="input-group">
                        <h2 style="color:#172554">Agregar Aeropuerto</h2>
                        <label for="idAeropuerto">ID Aeropuerto:</label>
                        <input type="text" id="idAeropuerto" name="idAeropuerto" required><br><br>
                    </div>

                    <div class="input-group">

                        <label for="ciudadAeropuerto">Ciudad Aeropuerto:</label>
                        <input type="text" id="ciudadAeropuerto" name="ciudadAeropuerto" required><br><br>
                    </div>
                    <div class="modal-buttons">
                        <button type="submit" class="modify-button" name="agregar_aeropuerto" id="confirm">Guardar</button>
                        <button id="cancel" class="cancel-button">Cancelar</button>
                    </div>

                </form>
            </div>
        </div>

        <script src="../js/script.js"></script>
        <script>
           
            document.addEventListener("DOMContentLoaded", function() {
                var deleteButtons = document.querySelectorAll(".delete-button");

                deleteButtons.forEach(function(button) {
                    button.addEventListener("click", function(event) {
                        event.preventDefault();

                        var idaeropuerto = button.getAttribute("data-id");

                        var confirmDelete = confirm("Desea borrar?");

                        if (confirmDelete) {
                            var xhr = new XMLHttpRequest();
                            xhr.open("POST", "aeropuertos_mod.php", true);
                            xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                            xhr.onreadystatechange = function() {
                                if (xhr.readyState === XMLHttpRequest.DONE) {
                                    if (xhr.status === 200) {
                                        location.reload(); 
                                    } else {
                                        alert("Error deleting record.");
                                    }
                                }
                            };
                            xhr.send("idAeropuerto=" + idaeropuerto);
                        }
                    });
                });
            });
        </script>

</body>

</html>