<?php
include('server.php');
// Verify if the user is logged in
if (!isset($_SESSION['correoCliente']) || !isset($_SESSION['role'])) {
    header("Location: login.php");
    exit();
}

// Verify if the user has the role 'admin'
if ($_SESSION['role'] !== 'admin') {
    // Redirect to client dashboard if not an admin
    header("Location: cliente_dashboard.php");
    exit();
}

if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['correoCliente']);
    header("location: login.php");
}

//Query to get all the flights, and feed them to options in the select tags for modify modal
$aeronaveQuery = "SELECT idaeronave, tipoAeronave FROM aeronave";
$aeronaveResult = $db->query($aeronaveQuery);

$aeropuertoQuery = "SELECT idAeropuerto, ciudadAeropuerto FROM aeropuerto";
$aeropuertoResult = $db->query($aeropuertoQuery)
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/styles.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Francois+One&family=Wix+Madefor+Display:wght@400;500&display=swap" rel="stylesheet">
    <title>flightScanner</title>

    <style>

    </style>


</head>

<body>

    <?php include 'menu_admin.php'; ?>


    <div class="flightcontent">
        <?php


        if (isset($modifiedSuccessfully) && $modifiedSuccessfully) {
            echo ' <div style="background-color: #c6efce;
            color: #006100;
            padding: 10px;
            border: 1px solid #006100;
            border-radius: 5px;
            margin: 10px 0;" class="success-message">Vuelo modificado correctamente.</div>';
        }
        ?>
        <div class="input-group">
            <h2 style="color:#172554">Eliminar vuelo</h2>
        </div>

        <!-- Vuelo table, generated by query -->
        <table border="1">
            <tr>
                <th>ID</th>
                <th>Origen</th>
                <th>Destino</th>
                <th>Aeronave</th>
                <th>Tipo Aeronave</th>
                <th>Fecha</th>
                <th>Arribado</th>
                <th>Estado</th>
                <th></th>
                <th></th>
            </tr>

            <?php
            //Query to generate vuelo table
            $sql = "SELECT * FROM Vuelo";
            $result = $db->query($sql);

            if ($result->num_rows > 0) {
                while ($row = $result->fetch_assoc()) {
                    echo "<tr>";
                    echo "<td>" . $row["idVuelo"] . "</td>";
                    echo "<td>" . $row["vueloOrigen"] . "</td>";
                    echo "<td>" . $row["vueloDestino"] . "</td>";
                    echo "<td>" . $row["idAeronave"] . "</td>";
                    echo "<td>" . $row["tipoAeronave"] . "</td>";
                    echo "<td>" . $row["fechaVuelo"] . "</td>";
                    echo "<td>" . $row["vueloArribado"] . "</td>";

                    echo "<td>" . $row["estado"] . "</td>";
                    echo "<td><a href='#' class='delete-button' onclick='openDeleteModal(" . $row["idVuelo"] . ")'>Borrar</a></td>";
                    echo "<td><a href='#' class='modify-button' onclick='openModifyModal(" . $row["idVuelo"] . ", \"" . $row["vueloOrigen"] . "\", \"" . $row["vueloDestino"] . "\", " . $row["idAeronave"] . ", \"" . $row["fechaVuelo"] . "\", \"" . $row["vueloArribado"] . "\", \"" . $row["estado"] . "\")'>Modificar</a></td>";
                    echo "</tr>";
                }
            } else {
                echo "<tr><td colspan='9'>No data found</td></tr>";
            }
            ?>

        </table>

        <!-- Delete modal, to confirm deletion of table vuelos registry through ID -->
        <div id="deleteModal" class="modal">
            <div class="modal-content">
                <span class="close" id="modalClose">&times;</span>
                <p>¿Quiere borrar este vuelo de manera permanente?</p>
                <div class="modal-buttons">
                    <button class="delete-button" id="confirmDelete">Borrar</button>
                    <button id="cancelDelete" class="cancel-button">Cancelar</button>
                </div>
            </div>
        </div>

        <!-- Modify modal, to confirm modification of table vuelos registry through ID -->

        <div id="modifyModal" class="modal">
            <div class="modal-content">
                <span class="close" id="modalClose">&times;</span>
                <form method="post" action="modify_vuelo.php">
                    <input type="hidden" name="id" id="flightId" value="">
                    <div class="input-group">
                        <label for="vueloOrigen">Origen del vuelo:</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" name="vueloOrigen" id="vueloOrigen">
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija el
                                Aeropuerto de Origen</option>
                            <?php
                            $aeropuertoResult->data_seek(0);
                            while ($row = $aeropuertoResult->fetch_assoc()) {
                                echo '<option style="color: black; background-color: white;" value="' . $row["idAeropuerto"] . '">' . $row["ciudadAeropuerto"] . '</option>';
                            }
                            ?>
                        </select>
                    </div>

                    <div class="input-group">
                        <label for="vueloDestino">Destino del vuelo:</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" name="vueloDestino" id="vueloDestino">
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija el
                                Aeropuerto de Destino</option>
                            <?php
                            $aeropuertoResult->data_seek(0);
                            while ($row = $aeropuertoResult->fetch_assoc()) {
                                echo '<option style="color: black; background-color: white;" value="' . $row["idAeropuerto"] . '">' . $row["ciudadAeropuerto"] . '</option>';
                            }
                            ?>
                        </select>
                        <br>
                    </div>

                    <div class="input-group">
                        <label for="idAeronave">Aeronave:</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" name="idAeronave" id="idAeronave">
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija la
                                aeronave</option>
                            <?php
                            while ($row = $aeronaveResult->fetch_assoc()) {
                                echo '<option style="color: black; background-color: white;" value="' . $row["idaeronave"] . '">' . $row["tipoAeronave"] . '</option>';
                            }
                            ?>
                        </select>
                        <br>
                    </div>

                    <div class="input-group">
                        <label for="fechaVuelo">Fecha del Vuelo:</label>
                        <input type="date" name="fechaVuelo" id="fechaVuelo" min="<?php echo date("Y-m-d"); ?>" required>
                        <br>
                    </div>

                    <div class="input-group">
                        <label for="vueloArribado">Estado de arribo:</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" type="text" name="vueloArribado" id="vueloArribado" required>
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija el
                                estado de arribo del vuelo</option>
                            <option style="color: black; background-color: white;">No arribado</option>
                            <option style="color: black; background-color: white;">Arribado</option>
                        </select>
                        <br>
                    </div>



                    <div class="input-group">
                        <label for="estado">Estado de actividad:</label>
                        <select style="color: black;  width: 100%; padding: 10px; font-size: 16px;  border: 1px solid #ccc;  border-radius: 5px; background-color: white;" type="text" name="estado" id="estado" required>
                            <option style="color: black; background-color: white;" value="" selected disabled>Elija el
                                estado del vuelo</option>
                            <option style="color: black; background-color: white;">Activo</option>
                            <option style="color: black; background-color: white;">Pendiente</option>
                        </select>
                        <br>
                    </div>



                    <div class="modal-buttons">
                        <button type="submit" class="modify-button" name="actualizar_vuelo" id="confirm">Guardar</button>
                        <button id="cancel" class="cancel-button">Cancelar</button>
                    </div>
                </form>
            </div>
        </div>

        <script src="../js/script.js"></script>

</body>

</html>